### ISSUE TITLE
Resolution on the S21FE to HD+ (1560X720)

### ISSUE THREAD

**Issue by diegogyn** [tribalfs/GalaxyMaxHzPub#78]
When I change the resolution on the S21FE to HD+ (1560X720) the top bar keeps cutting and the front camera hole is out of place (the curve of the edges also increases). Is there any way to change the resolution and keep the screen proportions? (It will be great because it will save a lot of battery)

**Comment by tribalfs** [comment]
Try to reload profile while connected to internet. 
We fixed profile in our backend (should be 1600 x720)

**Comment by diegogyn** [comment]
Still having the same problem as shown below: **https://imgur.com/a/41CjhR1**

I believe it's not possible to change the resolution on the SM-G990E because of the hole-punch camera, but I'm not sure it might be necessary to change some other setting.

Thanks!
